- simulators/as.py
- simulators/utils.py
AS protocol and an utils.py module containing some common functions, that can be shared between `systems`.
> Fix issue 2

- simulators/active_surface.py
- tests/test_active_surface.py
Added tests for each active surface drivers commands in [test_active_surface.py](https://github.com/discos/simulators/blob/fix-issue-9/tests/test_active_surface.py), both with correct values and with out of range parameters.
> Added tests for each active surface drivers commands

- simulators/active_surface.py
Fixed drivers startup/restart delay issue, also fixed some minor bugs.
> Fixed drivers startup/restart delay issue.

- simulators/active_surface.py
> Changed helper methods names to explicit ones, this fixes issue #15

- simulators/utils.py
> Fix for issue #18, utils.py methods documented.

- simulators/utils.py
Now the int_to_twos method raises a ValueError for out of range values.
> Fix for issue #21

- simulators/utils.py
> Fix #23: added example for ValueError test case.

- simulators/utils.py
> Fix #28: remove unused import

- tests/test_utils.py
> Fix #4: Add test for utils.py

- simulators/active_surface.py
- tests/test_active_surface.py
Also, a few minor corrections were made.
> Fix #35: now every active_surface protocol method change drivers status.

- simulators/acu.py
- tests/test_acu.py
The ACU system provides a status message (for now all parameters are set to 0) and a parse() interface (which for now does not call any system method or function).
> First ACU system implementation.

- setup.py
> Fix #101. Now setup.py is able to locate subpackages.

- simulators/active_surface.py
- simulators/if_distributor.py
Coverage is decreased and the branch `fix-issue-111' shouldn't be merged before a fix. Reverting changes.
> Revert "Fix #111. Fixed updated linter errors."

- scripts/discos-simulator
- simulators/if_distributor/IFD_14_channels.py
- simulators/if_distributor/__init__.py
- simulators/utils.py
- tests/test_if_distributor.py
Also reworked if_distributor to accept multiple configurations.
> Fix #142, `discos-simulator` script enhanced.

- simulators/if_distributor/IFD.py
- simulators/if_distributor/IFD_14_channels.py
- simulators/if_distributor/__init__.py
- tests/test_if_distributor.py
Also a little rework on the past IFDistributor has been made.
> Fix #137, implemented the new IFDistributor simulator and its tests.

- setup.py
- simulators/active_surface/__init__.py
- simulators/active_surface/command_library.py
- simulators/active_surface/usd.py
- tests/test_active_surface.py
- tox.ini
The command library serves the purpose of composing the commands to be sent to the active surface module while performing tests.
Also, the behavior of the USD positioning procedures has been reworked, now the USDs should act similarly to yhe real ones.
> Fix #150, added a command library to the active surface module.

- doc/api.rst
- requirements.txt
- simulators/utils.py
- tests/test_utils.py
Now the package relies on `astropy` python package.
> Fix #172, fixed datetime to mjd and vice versa conversion

- .coveragerc
- simulators/acu/__init__.py
- simulators/common.py
- simulators/server.py
- tests/test_acu.py
- tests/test_server.py
- tox.ini
> Fix #174, replaced System.get_message with subscribe and unsubscribe

- simulators/calmux/__init__.py
- simulators/if_distributor/IFD.py
- tests/test_calmux.py
Also, corrected a very small issue with the IFD simulator.
> Fix #180, written the calmux simulator and its tests

- doc/developers.rst
- doc/index.rst
- doc/setup.rst
- doc/users.rst
Also, documented the `SendingSystem` `subscribe` and `unsubscribe` methods.
> Partial fix for #170, updated documentation with requirements

- simulators/active_surface/__init__.py
- simulators/acu/__init__.py
- simulators/calmux/__init__.py
- simulators/if_distributor/__init__.py
This will allow the simulators to be reached from different machines
> Fix #185, exposed the simulators to all newtork interfaces

- simulators/active_surface/__init__.py
- simulators/acu/__init__.py
- simulators/calmux/__init__.py
- simulators/if_distributor/__init__.py
- simulators/server.py
- tests/test_acu.py
- tests/test_server.py
Added tests for UDP servers, also added some tests for ACU limits
> Fix #193, added UDP server feature.

- .coveragerc
- simulators/acu/axis_status.py
- simulators/server.py
- simulators/weather_station/__init__.py
- tests/test_weather_station.py
Also, some minor fixes to coverage reporting
> Added the weather station simulator

- doc/api.rst
- doc/developers.rst
- doc/setup.rst
- simulators/active_surface/__init__.py
- simulators/active_surface/command_library.py
- simulators/active_surface/usd.py
- simulators/utils.py
- tests/test_active_surface.py
Now the positioning of each USD is handled by a single thread for each line, instead of having a thread for each USD, which used to load too much the machine (more than 1000 concurrent threads). The whole positioning strategy has been refactored, along with some other fixes and improvements. Tests have been updated as well, in order to grant as much coverage as possible. The documentation though has to be updated ASAP in order for this branch to be merged.
> Fix #200, improved AS simulator

- simulators/mscu/__init__.py
- simulators/mscu/parameters.py
- simulators/mscu/servo.py
- tests/test_mscu.py
- tests/test_server.py
Tests need to be written before merging this onto master
> Fix #202, added MSCU simulator

- .coveragerc
- simulators/backend/__init__.py
- simulators/backend/genericbackend.py
- simulators/backend/grammar.py
- simulators/server.py
- simulators/utils.py
- tests/test_backend.py
- tests/test_server.py
In order to accomodate some needs for the new backend simulator, a few minor changes were introduced in the framework.
> Fix #205, added backend simulator

- simulators/receiver/__init__.py
- simulators/receiver/slaves.py
- tests/test_receiver.py
Also, fixed a wrong behavior with SD and VLBI modes
> Fix #231, added a configuration for a 7 feeds K band SRT receiver simulator

- simulators/totalpower/__init__.py
- tests/test_totalpower.py
The TotalPower hardware boards are numbered starting from the number 1, not from the number 0. Behavior corrected
> Issue #226, corrected a wrong behavior of the TotalPower simulator

- simulators/minor_servos/__init__.py
- tests/test_minor_servos.py
This simulator focuses on the protocol correctness, it is by no means a 1:1 functional simulator attempt. It can be improved in the future by correctly implementing the PRESET and PROGRAMTRACK behavior.
> Fix #309, implemented OR7 minor servos simulator

- .actrc
- .github/workflows/ci_tests.yml
- .github/workflows/scheduled_py3_tests.yml
- .readthedocs.yaml
- doc/content/developers.rst
- doc/content/framework.rst
- doc/content/users.rst
- doc/doc_requirements.txt
- doc/requirements.txt
- simulators/server.py
- testing_requirements.txt
A new tool for offline testing was introduced and documented in the documentation.
> Fix #269, updated documentation for Python 3

- doc/content/users.rst
- simulators/dbesm/DBESM.py
- simulators/dbesm/__init__.py
- tests/test_dbesm.py
Implemented DBESM simulator and its tests
> Fix issue 310

- simulators/minor_servos/__init__.py
Now it reflects better the actual minor servos behavior
> Fix #323, improved minor servos program track behavior

- simulators/receiver/__init__.py
@aorlati you can find here the ports used by the simulator. You can add them in the testing CDBs whenever you feel like it.
> Fix #336, added C band - 5GHz receiver simulator
